services:
  mysql:
    image: mysql:9.1.0
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tourism

  tomcat:
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:8080

volumes:
  mysql-data:
